### ISSUE TITLE
different with langchain

### ISSUE THREAD

**Issue by FieldRen** [continuum-llms/chatgpt-memory#22]
Hi, great work! But what's the difference with langchain?
https://python.langchain.com/en/latest/modules/memory/getting_started.html

**Comment by shahrukhx01** [comment]
Hi @FieldRen, The current memory implementations in langchain are heuristic-based, meaning you are using all the conversation history or the last k messages. Hence, such approaches are not adaptive if the user changes the topic which was part of earlier conversation history, the heuristic approaches might miss it because of token overflow or it could be outside the last k messages. We in our case try to make the history component adaptive hence, it only brings the previous k messages which are relevant to the current message from the entire history. Hence, adding more relevant context in the prompt and never running out of token length. Below is an example:

<img src="https://d33wubrfki0l68.cloudfront.net/88c3a63dd5bdf04ad00da7f6b3a192f2340b271a/058e3/images/langchain-conversational-memory-3.png">


If you want to delve deeper into current memory implementations of langchain, here is a great [article](https://www.pinecone.io/learn/langchain-conversational-memory/).

**Comment by FieldRen** [comment]
I got it, It's a very good idea.Thanks for your explanation!
