### ISSUE TITLE
Generates irrelevant / too much conversation?

### ISSUE THREAD

**Issue by sarperdag** [continuum-llms/chatgpt-memory#24]
Sometimes, when I simple just type "hi" as an input. The response is a whole conversation generated between human and the assistant. I only want assistant's responses to be generated. Why might this be happening?

**Comment by shahrukhx01** [comment]
@sarperdag It seems you are starting another conversation in the existing session. In that case, you can just explicitly initiate a new chat session by not sending the `conversation_id`, and in the response you'd receive a new `conversation_id` for the new session.

**Comment by sarperdag** [comment]
Thanks but I think I wasn't able to explain the problem clearly. Here's a screenshot of what's happening. The conversation id is 1, I'm just starting the conversation, redis db is totally empty, and I'm getting this as the response. 

![2886e273-e49b-49d5-9898-383898b99a3e](https://user-images.githubusercontent.com/47207/231888943-9a617a5d-4f0e-4060-af75-015680935fc5.JPG)

**Comment by shahrukhx01** [comment]
@sarperdag, it seems like it this problem is occurring since you appended an additional prompt template and we already have a fixed prompt template. If you'd like to change the prompt template to yours you can do so by modifying the[ `get_prompt`](https://github.com/continuum-llms/chatgpt-memory/blob/main/chatgpt_memory/utils/openai_utils.py#L126) utility function. Please do let us know if this resolves this behavior.

**Comment by sarperdag** [comment]
Nope, I'm modifying the prompt template under the get_prompt function. There is no additional prompt I'm appending. The issue occurs randomly, like %20 of the time. Not always.

**Comment by shahrukhx01** [comment]
@sarperdag I suspect this could be occurring due to how the prompt is formulated, maybe rephrasing it somehow might help it.
