### ISSUE TITLE
Retaining conversation id's between process executions?

### ISSUE THREAD

**Issue by djriffel** [continuum-llms/chatgpt-memory#31]
Hello, I just started messing with this library and from what I can tell, the conversation ID's are only valid during an active process session, but if the process/application is restarted, then there seems to no longer be any context when trying to re-use any of these previous conversation ID's. 

Is this expected behavior? Is there a way to make these previous conversation ID's re-usable across process executions?

**Comment by shahrukhx01** [comment]
Hi @djriffel, yes this is the expected behaviour since we expected a conversational session to be brief. In order to re-use any of the ids, you can persist them either externally somewhere (i.e., file, or memory). Otherwise, you can use Redis itself to do that, the conversational history would persist in Redis unless you instantiate `RedisDataStore` with the flag `do_flush_data`.

**Comment by djriffel** [comment]
So I think I have a little more info on what's going on here. While the `do_flush_data` parameter will in fact prevent deletion of documents upon construction of the `RedisDataStore`, the behavior during a service restart is effectively the same either way. This is because in the _destructor_ of the `MemoryManager` it will call the flush method anyways via `self.datastore.flush_all_documents()` on line 70 in the `clear()` method.

One thing that made it more confusing for me, and a bit intermittent, is that I would rapidly hit CTRL+C out of habit, which would sometimes quit the process too fast before it could perform this destructor logic.

Having said all that. This seems like it would behaviorally be a bug, no? Because if one were to provide the False value in the `do_flush_data` parameter (which is actually the default value, by the way), then would it not be out of line with expectations if it would clear it anyways after the process quits? If you disagree in that, I suppose the follow-up question would be: How can this expected behavior be invoked/reconciled with the library in its current state?

**Comment by shahrukhx01** [comment]
@nps1ngh shall we disable this behavior [here](https://github.com/continuum-llms/chatgpt-memory/blob/ee08cccf903ea356ef08dd80b0f12e20c1763a97/chatgpt_memory/memory/manager.py#L70). 
Because as described above you'd lose memory if you restart the process. WDYT?

**Comment by nps1ngh** [comment]
Yeah, we should change that 👍

**Comment by nps1ngh** [comment]
Hi, thanks a lot for your interest in the project.

Due to time constraints, we are unable to continue development on this repository.

Please check out OpenAI's official retrieval plugin, offering similar functionality and active development: [openai/chatgpt-retrieval-plugin](https://github.com/openai/chatgpt-retrieval-plugin)
