### ISSUE TITLE
update pip package 

### ISSUE THREAD

**Issue by scwall** [continuum-llms/chatgpt-memory#36]
Hello,

I'm starting to use your package but it doesn't correspond to the version on pypi, I've cloned the repository and I'm having fun modifying the different files for the moment however can you update the package?

https://pypi.org/project/chatgpt-memory/0.0.1/

Are you going to continue updating it? Or don't you have enough volunteers for maintenance? 

I'd like to know this before going any further on my own. 

Thank you in advance for your answers.

**Comment by nps1ngh** [comment]
Hi, thanks a lot for your interest in the project.

Due to time constraints, we are unable to continue development on this repository.

Please check out OpenAI's official retrieval plugin, offering similar functionality and active development: [openai/chatgpt-retrieval-plugin](https://github.com/openai/chatgpt-retrieval-plugin)
